sudo: required
services:
  - docker

before_install:
  - docker build -t harshil2612/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harshil2612/react-test npm test

after_success:
  - docker build -t harshil2612/multi-client ./client
  - docker build -t harshil2612/multi-nginx ./nginx
  - docker build -t harshil2612/multi-server ./server
  - docker build -t harshil2612/multi-worker ./worker

  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push harshil2612/multi-client
  - docker push harshil2612/multi-nginx
  - docker push harshil2612/multi-server
  - docker push harshil2612/multi-worker
